version: '3.1'
services:
  app:
    container_name: keeper_0.0.1
    image: keeper_0.0.1
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keeper
      - POSTGRES_PASSWORD=keeper!
      - POSTGRES_DB=electricity_keeper
